### ISSUE TITLE
Implement the Sign-in with Google

### ISSUE THREAD

**Issue by mathrmartins** [gameguild-gg/website#29]
## User Story:
As a user who prefers convenient authentication methods, I want to be able to sign in seamlessly with my Google account.

## Description:
As a user, I want the option to sign in or sign up using my Google account to streamline the authentication process. This requires implementing the Google OAuth Provider within the NextAuth.js configuration. Additionally, I expect to find a "Sign in with Google" button on the sign-in page. Clicking this button should initiate the sign-in process via Next.js Server Action.

During the sign-in process, upon clicking the "Sign in with Google" button, I expect to be redirected to the Google authentication page to enter my credentials. After completing the sign-in process, I should be redirected back to the application and logged in.

Moreover, I anticipate that the sign-in process with Google will seamlessly integrate with the API backend built on Nest.js, ensuring a smooth user experience. Additionally, I would appreciate the option to enable One Tap Sign-in with Google for even faster authentication.

In summary, this user story aims to provide users with the convenience of signing in and signing up using their Google accounts while ensuring a seamless and efficient authentication process.

## Requirements:
- [x] Implement the Google Provider in the NextAuth.js configuration.
- [x] Implement the Next.js Server Action to initiate the Sign-in with Google process.
- [x] Manage the Sign-in with Google process in the NextAuth.js sign-in callback.
- [x] Integrate the Sign-in with Google with the backend API (Nest.js).
- [ ] #63
- [x] Create the "Sign in with Google" button with its variations as specified in the [Sign in with Google Branding Guidelines](https://developers.google.com/identity/branding-guidelines).
- [x] Add the "Sign in with Google" button on the sign-in page.
- [x] Add the "Sign up with Google" button on the sign-in page.

**Comment by tolstenko** [comment]
Mostly implemented.
